import json
import os
import sys

# Ensure we can import from local folders relative to this script
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from parsers.prowler_parser import ProwlerParser

def generate_layer(input_file, output_file):
    print(f"Reading scan data from: {input_file}")
    
    # 1. Initialize the Parser
    parser = ProwlerParser()
    
    # 2. Get techniques from the Prowler scan
    try:
        techniques_list = parser.parse(input_file)
    except FileNotFoundError:
        print(f"ERROR: Could not find input file: {input_file}")
        return
    except Exception as e:
        print(f"ERROR: Failed to parse file. Reason: {e}")
        return

    # 3. Create the MITRE Layer JSON structure
    layer_json = {
        "name": "Auto-Generated Security Coverage",
        "versions": {
            "attack": "13",
            "navigator": "4.8.1"
        },
        "domain": "enterprise-attack",
        "description": "Visualization of Prowler security failures generated by CI/CD",
        "filters": {
            "platforms": ["AWS", "Linux", "Windows", "macOS"]
        },
        "techniques": techniques_list,
        "gradient": {
            "colors": ["#ffffff", "#ff6666", "#ff0000"],
            "minValue": 0,
            "maxValue": 1
        },
        "legendItems": [
            {
                "label": "Security Control Failed",
                "color": "#ff0000"
            }
        ]
    }

    # 4. Write to file
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, 'w') as f:
        json.dump(layer_json, f, indent=4)
    
    print(f"SUCCESS: Layer generated at {output_file}")
    print(f"Mapped {len(techniques_list)} techniques from the scan.")

if __name__ == "__main__":
    # Paths setup
    base_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(base_dir)
    
    # DEFAULT: Use sample data
    INPUT_PATH = os.path.join(project_root, "samples", "prowler-sample.json")
    OUTPUT_PATH = os.path.join(project_root, "generated_layers", "prowler_layer.json")

    # OVERRIDE: If user provided an argument
    # Example usage: python3 app/main.py /path/to/real_scan.json
    if len(sys.argv) > 1:
        user_input = sys.argv[1]
        if os.path.exists(user_input):
            INPUT_PATH = user_input
            # If user provides custom input, we still save to the standard output location
            # so the web server can find it.
        else:
            print(f"WARNING: Provided file '{user_input}' does not exist. Using default sample.")

    generate_layer(INPUT_PATH, OUTPUT_PATH)